version: '3.8'

services:
  tu-nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: tu-nginx
    restart: unless-stopped
    environment:
      RABBITMQ_USER: ${RABBITMQ_DEFAULT_USER:-admin}
      RABBITMQ_PASS: ${RABBITMQ_DEFAULT_PASS:-admin}
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx/mime.types:/etc/nginx/mime.types
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/ssl:/etc/nginx/ssl:ro
    networks:
      - tidy-url-network

  tu-rabbitmq:
    image: rabbitmq:3-management
    container_name: tu-rabbitmq
    restart: unless-stopped
    ports:
      - "15672:15672"
      - "5672:5672"
      - "61613:61613"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-admin}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-admin}
      RABBITMQ_PLUGINS: "rabbitmq_management rabbitmq_stomp"
    networks:
      - tidy-url-network

  tu-memcached:
    image: memcached
    container_name: tu-memcached
    restart: unless-stopped
    ports:
      - "11211:11211"
    command: ["-m", "512"]
    networks:
      - tidy-url-network

volumes:
  minio_data:
    driver: local

networks:
  tidy-url-network:
    external: true