// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.24.4
// source: proto/analytics.proto

package analytics

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnalyticsService_GetGeneralStats_FullMethodName   = "/analytics.AnalyticsService/GetGeneralStats"
	AnalyticsService_GetClicksPerDay_FullMethodName   = "/analytics.AnalyticsService/GetClicksPerDay"
	AnalyticsService_GetCountriesStats_FullMethodName = "/analytics.AnalyticsService/GetCountriesStats"
	AnalyticsService_GetDeviceStats_FullMethodName    = "/analytics.AnalyticsService/GetDeviceStats"
	AnalyticsService_GetBrowserStats_FullMethodName   = "/analytics.AnalyticsService/GetBrowserStats"
	AnalyticsService_GetOSStats_FullMethodName        = "/analytics.AnalyticsService/GetOSStats"
)

// AnalyticsServiceClient is the client API for AnalyticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnalyticsServiceClient interface {
	GetGeneralStats(ctx context.Context, in *AnalyticsRequest, opts ...grpc.CallOption) (*AnalyticsResponse, error)
	GetClicksPerDay(ctx context.Context, in *AnalyticsCleanRequest, opts ...grpc.CallOption) (*ClicksByDayResponse, error)
	GetCountriesStats(ctx context.Context, in *AnalyticsRequest, opts ...grpc.CallOption) (*CountryResponse, error)
	GetDeviceStats(ctx context.Context, in *AnalyticsRequest, opts ...grpc.CallOption) (*DeviceResponse, error)
	GetBrowserStats(ctx context.Context, in *AnalyticsRequest, opts ...grpc.CallOption) (*BrowserResponse, error)
	GetOSStats(ctx context.Context, in *AnalyticsRequest, opts ...grpc.CallOption) (*OSResponse, error)
}

type analyticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyticsServiceClient(cc grpc.ClientConnInterface) AnalyticsServiceClient {
	return &analyticsServiceClient{cc}
}

func (c *analyticsServiceClient) GetGeneralStats(ctx context.Context, in *AnalyticsRequest, opts ...grpc.CallOption) (*AnalyticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyticsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetGeneralStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetClicksPerDay(ctx context.Context, in *AnalyticsCleanRequest, opts ...grpc.CallOption) (*ClicksByDayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClicksByDayResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetClicksPerDay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetCountriesStats(ctx context.Context, in *AnalyticsRequest, opts ...grpc.CallOption) (*CountryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountryResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetCountriesStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetDeviceStats(ctx context.Context, in *AnalyticsRequest, opts ...grpc.CallOption) (*DeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetDeviceStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetBrowserStats(ctx context.Context, in *AnalyticsRequest, opts ...grpc.CallOption) (*BrowserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BrowserResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetBrowserStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetOSStats(ctx context.Context, in *AnalyticsRequest, opts ...grpc.CallOption) (*OSResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OSResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetOSStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyticsServiceServer is the server API for AnalyticsService service.
// All implementations must embed UnimplementedAnalyticsServiceServer
// for forward compatibility.
type AnalyticsServiceServer interface {
	GetGeneralStats(context.Context, *AnalyticsRequest) (*AnalyticsResponse, error)
	GetClicksPerDay(context.Context, *AnalyticsCleanRequest) (*ClicksByDayResponse, error)
	GetCountriesStats(context.Context, *AnalyticsRequest) (*CountryResponse, error)
	GetDeviceStats(context.Context, *AnalyticsRequest) (*DeviceResponse, error)
	GetBrowserStats(context.Context, *AnalyticsRequest) (*BrowserResponse, error)
	GetOSStats(context.Context, *AnalyticsRequest) (*OSResponse, error)
	mustEmbedUnimplementedAnalyticsServiceServer()
}

// UnimplementedAnalyticsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalyticsServiceServer struct{}

func (UnimplementedAnalyticsServiceServer) GetGeneralStats(context.Context, *AnalyticsRequest) (*AnalyticsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGeneralStats not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetClicksPerDay(context.Context, *AnalyticsCleanRequest) (*ClicksByDayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClicksPerDay not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetCountriesStats(context.Context, *AnalyticsRequest) (*CountryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCountriesStats not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetDeviceStats(context.Context, *AnalyticsRequest) (*DeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeviceStats not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetBrowserStats(context.Context, *AnalyticsRequest) (*BrowserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBrowserStats not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetOSStats(context.Context, *AnalyticsRequest) (*OSResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOSStats not implemented")
}
func (UnimplementedAnalyticsServiceServer) mustEmbedUnimplementedAnalyticsServiceServer() {}
func (UnimplementedAnalyticsServiceServer) testEmbeddedByValue()                          {}

// UnsafeAnalyticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyticsServiceServer will
// result in compilation errors.
type UnsafeAnalyticsServiceServer interface {
	mustEmbedUnimplementedAnalyticsServiceServer()
}

func RegisterAnalyticsServiceServer(s grpc.ServiceRegistrar, srv AnalyticsServiceServer) {
	// If the following call pancis, it indicates UnimplementedAnalyticsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnalyticsService_ServiceDesc, srv)
}

func _AnalyticsService_GetGeneralStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetGeneralStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetGeneralStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetGeneralStats(ctx, req.(*AnalyticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetClicksPerDay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyticsCleanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetClicksPerDay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetClicksPerDay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetClicksPerDay(ctx, req.(*AnalyticsCleanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetCountriesStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetCountriesStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetCountriesStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetCountriesStats(ctx, req.(*AnalyticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetDeviceStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetDeviceStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetDeviceStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetDeviceStats(ctx, req.(*AnalyticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetBrowserStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetBrowserStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetBrowserStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetBrowserStats(ctx, req.(*AnalyticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetOSStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetOSStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetOSStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetOSStats(ctx, req.(*AnalyticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalyticsService_ServiceDesc is the grpc.ServiceDesc for AnalyticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalyticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "analytics.AnalyticsService",
	HandlerType: (*AnalyticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGeneralStats",
			Handler:    _AnalyticsService_GetGeneralStats_Handler,
		},
		{
			MethodName: "GetClicksPerDay",
			Handler:    _AnalyticsService_GetClicksPerDay_Handler,
		},
		{
			MethodName: "GetCountriesStats",
			Handler:    _AnalyticsService_GetCountriesStats_Handler,
		},
		{
			MethodName: "GetDeviceStats",
			Handler:    _AnalyticsService_GetDeviceStats_Handler,
		},
		{
			MethodName: "GetBrowserStats",
			Handler:    _AnalyticsService_GetBrowserStats_Handler,
		},
		{
			MethodName: "GetOSStats",
			Handler:    _AnalyticsService_GetOSStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/analytics.proto",
}
