services:
  tu-user-db:
    image: postgres:latest
    container_name: tu-user-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: unless-stopped
    volumes:
      - tu_user_db_data:/var/lib/postgresql/data
    networks:
      - tidy-url-network

  tu-user-redis:
    container_name: tu-user-redis
    hostname: redis
    image: redis:latest
    volumes:
      - tu_user_redis_data:/data
    restart: unless-stopped
    networks:
      - tidy-url-network

  tu-user-backend:
    build:
      context: ./
      dockerfile: Dockerfile
      target: prod
    container_name: tu-user-backend
    ports:
      - "${SERVICE_PORT:-8000}:${SERVICE_PORT:-8000}"
    volumes:
      - ./:/app:cached
    depends_on:
      - tu-user-db
      - tu-user-redis
    environment:
      REDIS_ADDRESS: tu-user-redis:${REDIS_PORT:-6379}
      DB_HOST: tu-user-db
      DB_PORT: ${POSTGRES_PORT:-5432}
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      GIN_MODE: "release"
    restart: unless-stopped
    networks:
      - tidy-url-network

volumes:
  tu_user_db_data:
    driver: local
  tu_user_redis_data:
    driver: local

networks:
  tidy-url-network:
    external: true