version: "3.8"

services:
  tu-link-backend:
    build:
      context: ./
      dockerfile: Dockerfile
      target: dev
    container_name: tu-link-backend
    volumes:
      - ./:/app:cached
    command: air
    ports:
      - "5865:5864"
      - "${SERVICE_PORT:-8000}:${SERVICE_PORT:-8000}"
    networks:
      - tidy-url-network