version: '3.8'

services:
  tu-link-db:
    image: postgres:latest
    container_name: tu-link-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: unless-stopped
    volumes:
      - tu_link_db_data:/var/lib/postgresql/data
    networks:
      - tidy-url-network

  tu-link-keydb:
    container_name: tu-link-keydb
    image: eqalpha/keydb:latest
    volumes:
      - tu_link_keydb_data:/data
    restart: unless-stopped
    networks:
      - tidy-url-network

  tu-link-backend:
    build:
      context: ./
      dockerfile: Dockerfile
      target: prod
    container_name: tu-link-backend
    ports:
      - "${SERVICE_PORT:-8000}:${SERVICE_PORT:-8000}"
    volumes:
      - ./:/app:cached
    depends_on:
      - tu-link-db
      - tu-link-keydb
    environment:
      REDIS_ADDRESS: tu-link-keydb:${REDIS_PORT:-6379}
      DB_HOST: tu-link-db
      DB_PORT: ${POSTGRES_PORT:-5432}
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      GIN_MODE: "release"
    restart: unless-stopped
    networks:
      - tidy-url-network

volumes:
  tu_link_db_data:
    driver: local
  tu_link_keydb_data:
    driver: local

networks:
  tidy-url-network:
    external: true